/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.code.games;
import static hexlet.code.Cli.random;

public class Calc extends Game {

    private static final int MIN_NUM = -100;
    private static final int MAX_NUM = 100;
    private static final char[] OPERATORS = new char[]{'+', '*', '-'};

    public Calc() {
        super("Calc");
    }

    public static String getName() {
        return "Calc";
    }

    @Override
    public final String getRules() {
        return "What is the result of the expression?";
    }

    @Override
    public final String[] getQuestion() {
        final int a = random(MIN_NUM, MAX_NUM);
        final int b = random(MIN_NUM, MAX_NUM);
        final int opNum = random(OPERATORS.length);
        final char operator = OPERATORS[opNum];
        final String question = String.format(
                "%d %s %d",
                a,
                operator,
                b
        );
        final int answer = calc(a, b, operator);
        return new String[]{
            question,
            String.valueOf(answer)
        };
    }

    private static int calc(final int a, final int b, final char operator) {
        return switch (operator) {
            case '+' -> a + b;
            case '-' -> a - b;
            case '*' -> a * b;
            default -> throw new IllegalArgumentException("Unknown operator " + operator);
        };
    }
}
