/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.code.games;

public abstract class Game {
    private String name = "";

    public Game(final String val) {
        this.name = val;
    }

    public abstract String getRules();

    public abstract String[] getQuestion();
}
