/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.code.games;

import static hexlet.code.Cli.random;
import static java.lang.Math.max;

public class GCD extends Game {
    private static final int MIN_NUM = 1;
    private static final int MAX_NUM = 100;

    public GCD() {
        super("GCD");
    }

    public static String getName() {
        return "GCD";
    }

    @Override
    public final String getRules() {
        return "Find the greatest common divisor of given numbers.";
    }

    @Override
    public final String[] getQuestion() {
        final int a = random(MIN_NUM, MAX_NUM);
        final int b = random(MIN_NUM, MAX_NUM);
        final String question = String.format("%d %d", a, b);
        return new String[]{
            question,
            String.valueOf(gcd(a, b))
        };
    }

    private static int gcd(final int a, final int b) {
        int m = 1;
        if (a == b) {
            return a;
        }
        for (int i = 2; i <= max(a, b) / 2; i++) {
            if (a % i == 0 && b % i == 0) {
                m = i;
            }
        }
        return m;
    }
}
