/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.code.games;

import static hexlet.code.Cli.random;

public class Progression extends Game {
    private static final int MIN_STEP = 1;
    private static final int MAX_STEP = 50;
    private static final int MIN_LEN = 5;
    private static final int MAX_LEN = 15;
    private static final int MIN_START = -20;
    private static final int MAX_START = 20;

    public Progression() {
        super("Progression");
    }

    public static String getName() {
        return "Progression";
    }

    @Override
    public final String getRules() {
        return "What number is missing in the progression?";
    }

    @Override
    public final String[] getQuestion() {
        final int[] progression = generateProgression();
        final int hideIndex = random(progression.length);
        final String question = toStr(progression, hideIndex);
        return new String[]{
            question,
            String.valueOf(progression[hideIndex])
        };
    }

    private static String toStr(final int[] progression, final int hideIndex) {
        final StringBuilder sb = new StringBuilder();
        for (int i = 0; i < hideIndex; i++) {
            sb.append(progression[i]).append(" ");
        }
        sb.append(".. ");
        for (int i = hideIndex + 1; i < progression.length; i++) {
            sb.append(progression[i]).append(" ");
        }
        sb.deleteCharAt(sb.length() - 1);

        return sb.toString();
    }

    private static int[] generateProgression() {
        final int step = random(MIN_STEP, MAX_STEP);
        final int len = random(MIN_LEN, MAX_LEN);
        final int[] progression = new int[len];
        progression[0] = random(MIN_START, MAX_START);
        for (int i = 1; i < len; i++) {
            progression[i] = progression[i - 1] + step;
        }
        return progression;
    }
}
