/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.code;
import static hexlet.code.Cli.random;

public class Calc {

    private static final int MIN_NUM = -100;
    private static final int MAX_NUM = 100;
    private static final char[] OPERATORS = new char[]{'+', '*', '-'};

    public static String getRules() {
        return "What is the result of the expression?";
    }

    public static String getName() {
        return "Calc";
    }

    public static String[][] getQuestions(final int count) {
        final String[][] qa = new String[count][];
        for (int i = 0; i < count; i++) {
            qa[i] = getQuestion();
        }

        return qa;
    }

    private static String[] getQuestion() {
        final int a = random(MIN_NUM, MAX_NUM);
        final int b = random(MIN_NUM, MAX_NUM);
        final int opNum = random(OPERATORS.length);
        final char operator = OPERATORS[opNum];
        final String question = String.format(
                "%d %s %d",
                a,
                operator,
                b
        );
        final int answer = calc(a, b, operator);
        return new String[]{
            question,
            String.valueOf(answer)
        };
    }

    private static int calc(final int a, final int b, final char operator) {
        return switch (operator) {
            case '+' -> a + b;
            case '-' -> a - b;
            case '*' -> a * b;
            default -> throw new IllegalArgumentException("Unknown operator " + operator);
        };
    }


    public static String run() {
        System.out.println(getRules());
        int countRightAnswer = 0;
        final int victoryCount = 3;
        while (countRightAnswer < victoryCount) {
            String[] question = getQuestion();
            System.out.println("Question: " + question[0]);
            System.out.print("Your answer: ");
            String answer = Cli.nextLine();
            String rightAnswer = question[1];
            if (rightAnswer.equals(answer)) {
                System.out.println("Correct!");
                countRightAnswer++;
            } else {
                System.out.println("'" + answer + "' is wrong answer ;(. Correct answer was '" + rightAnswer + "'.");
                countRightAnswer = 0;
                return "Let's try again, ";
            }
        }
        return "Congratulations, ";
    }
}
