/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.code;

import java.util.Scanner;
public class Cli {
    public static void run() {
        System.out.println("Welcome to the Brain Games!");
        try (
            Scanner myObj = new Scanner(System.in)) {
            System.out.print("May I have your name? ");

            String userName = myObj.nextLine();  // Read user input
            System.out.println("Hello, " + userName + "!");  // Output user input
        }
    }
}
