/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.code;

import java.util.Scanner;
import java.util.Random;

public class Cli {
    static Scanner s = new Scanner(System.in);
    static Random RANDOM = new Random();

    public static String welcome() {
        System.out.println("Welcome to the Brain Games!");
        System.out.print("May I have your name? ");
        String userName = nextLine();
        System.out.println("Hello, " + userName + "!");
        return userName;
    }

    public static String nextLine() {
        return s.nextLine();
    }

    public static int random() {
        return RANDOM.nextInt();
    }
}
