/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.code;

public class Even {

    public static String run() {
        System.out.println("Answer 'yes' if the number is even, otherwise answer 'no'.");
        int countRightAnswer = 0;
        final int victoryCount = 3;
        while (countRightAnswer < victoryCount) {
            int random = Cli.random();
            System.out.println("Question: " + random);
            System.out.print("Your answer: ");
            String answer = Cli.nextLine();
            String rightAnswer = random % 2 == 0 ? "yes" : "no";
            if (rightAnswer.equals(answer)) {
                System.out.println("Correct!");
                countRightAnswer++;
            } else {
                System.out.println("'" + answer + "' is wrong answer ;(. Correct answer was '" + rightAnswer + "'.");
                countRightAnswer = 0;
                return "Let's try again, ";
            }
        }
        return "Congratulations, ";
    }
}
