/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.code;

import java.util.Scanner;
import java.util.Random;

public class Cli {
    private static Scanner s = new Scanner(System.in);
    private static Random rand = new Random();

    public static String welcome() {
        System.out.println("Welcome to the Brain Games!");
        System.out.print("May I have your name? ");
        String userName = nextLine();
        System.out.println("Hello, " + userName + "!");
        return userName;
    }

    public static String nextLine() {
        return s.nextLine();
    }

    public static int random() {
        return rand.nextInt();
    }

    public static int random(final int min, final int max) {
        return min + rand.nextInt(max - min + 1);
    }

    public static int random(final int bound) {
        return rand.nextInt(bound);
    }

    public static boolean bool() {
        return rand.nextBoolean();
    }
}
