/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.code.games;

import hexlet.code.Cli;

public class Even extends Game {
    public Even() {
        super("Even");
    }

    public static String getName() {
        return "Even";
    }

    @Override
    public final String getRules() {
        return "Answer 'yes' if the number is even,otherwise answer 'no'.";
    }

    @Override
    public final String[] getQuestion() {
        final int random = Cli.random();
        final String question = String.format(
                "%d",
                random
        );
        final String answer = random % 2 == 0 ? "yes" : "no";
        return new String[]{
            question,
            String.valueOf(answer)
        };
    }
}
